### ISSUE TITLE
the example is incomplete

### ISSUE THREAD

**Issue by d4e666** [mp911de/CleanArchitecture#1]
When I opened the OrderService there are several dependencies missing from download. Please upload all files.

**Comment by d4e666** [comment]
try to be consistend in your naming: the class is called Output as suffix, but your service uses Response as sufix. Did you even test the code????

**Comment by mp911de** [comment]
Thanks for your report. Please help me understand what you're missing or what should I upload. I usually do not heavily invest in manual tests. I rather use CI and test automation, see https://snap-ci.com/mp911de/CleanArchitecture/branch/master/logs/defaultPipeline/8/Maven
