### ISSUE TITLE
Internal Server Error when launching the app

### ISSUE THREAD

**Issue by srikrishnacj** [mp911de/CleanArchitecture#2]
Just download and run the maven command and opened it in browser. It show this error
mvn clean package jboss-as:run

![clean-arch](https://cloud.githubusercontent.com/assets/4404755/15074361/31ab8158-13bc-11e6-9717-b57cd8fb8845.png)

**Comment by mp911de** [comment]
Thanks for reporting. This issue is fixed. I also upgraded dependencies to WildFly 10.
